### ISSUE TITLE
release with der-parser 8

### ISSUE THREAD

**Issue by victorjulien** [rusticata/kerberos-parser#14]
Hi Pierre,

We're reviewing der-parser usage in Suricata, and we see 6.0.1 being pulled in through kerberos-parser 0.7.1. Are you planning a release that bumps to 8? I see the commit already exists.

(btw 0.7.1 is not tagged)

Thanks!

FYI, we're tracking things here https://redmine.openinfosecfoundation.org/issues/5994

**Comment by chifflier** [comment]
Hi @victorjulien ,

I'm catching back on all my crates!
I just tagged everything and uploaded a new version, so I'll close this issue.
BTW, the new `der-parser` is 9. If that is a problem and you require a release with before 8.0 exactly, just tell me and I'll see if it's possible.
Thanks!

**Comment by victorjulien** [comment]
Thanks @chifflier!
